using System;
using System.Collections.Generic;

#nullable disable

namespace AMSWebAPI.Models
{
    public partial class AmsDataBar
    {
        public int Id { get; set; }
        public DateTime Utc { get; set; }
        public short? C1 { get; set; }
        public short? C2 { get; set; }
        public short? C3 { get; set; }
        public short? C4 { get; set; }
        public short? C5 { get; set; }
        public short? C6 { get; set; }
        public short? C7 { get; set; }
        public short? C8 { get; set; }
        public short? C9 { get; set; }
        public short? C10 { get; set; }
        public short? C11 { get; set; }
        public short? C12 { get; set; }
        public short? C13 { get; set; }
        public short? C14 { get; set; }
        public short? C15 { get; set; }
        public short? C16 { get; set; }
        public short? C17 { get; set; }
        public short? C18 { get; set; }
        public short? C19 { get; set; }
        public short? C20 { get; set; }
        public short? C21 { get; set; }
        public short? C22 { get; set; }
        public short? C23 { get; set; }
        public short? C24 { get; set; }
        public short? C25 { get; set; }
        public short? C26 { get; set; }
        public short? C27 { get; set; }
        public short? C28 { get; set; }
        public short? C29 { get; set; }
        public short? C30 { get; set; }
        public short? C31 { get; set; }
        public short? C32 { get; set; }
        public short? C33 { get; set; }
        public short? C34 { get; set; }
        public short? C35 { get; set; }
        public short? C36 { get; set; }
        public short? C37 { get; set; }
        public short? C38 { get; set; }
        public short? C39 { get; set; }
        public short? C40 { get; set; }
        public short? C41 { get; set; }
        public short? C42 { get; set; }
        public short? C43 { get; set; }
        public short? C44 { get; set; }
        public short? C45 { get; set; }
        public short? C46 { get; set; }
        public short? C47 { get; set; }
        public short? C48 { get; set; }
        public short? C49 { get; set; }
        public short? C50 { get; set; }
        public short? C51 { get; set; }
        public short? C52 { get; set; }
        public short? C53 { get; set; }
        public short? C54 { get; set; }
        public short? C55 { get; set; }
        public short? C56 { get; set; }
        public short? C57 { get; set; }
        public short? C58 { get; set; }
        public short? C59 { get; set; }
        public short? C60 { get; set; }
        public short? C61 { get; set; }
        public short? C62 { get; set; }
        public short? C63 { get; set; }
        public short? C64 { get; set; }
        public short? C65 { get; set; }
        public short? C66 { get; set; }
        public short? C67 { get; set; }
        public short? C68 { get; set; }
        public short? C69 { get; set; }
        public short? C70 { get; set; }
        public short? C71 { get; set; }
        public short? C72 { get; set; }
        public short? C73 { get; set; }
        public short? C74 { get; set; }
        public short? C75 { get; set; }
        public short? C76 { get; set; }
        public short? C77 { get; set; }
        public short? C78 { get; set; }
        public short? C79 { get; set; }
        public short? C80 { get; set; }
        public short? C81 { get; set; }
        public short? C82 { get; set; }
        public short? C83 { get; set; }
        public short? C84 { get; set; }
        public short? C85 { get; set; }
        public short? C86 { get; set; }
        public short? C87 { get; set; }
        public short? C88 { get; set; }
        public short? C89 { get; set; }
        public short? C90 { get; set; }
        public short? C91 { get; set; }
        public short? C92 { get; set; }
        public short? C93 { get; set; }
        public short? C94 { get; set; }
        public short? C95 { get; set; }
        public short? C96 { get; set; }
        public short? C97 { get; set; }
        public short? C98 { get; set; }
        public short? C99 { get; set; }
        public short? C100 { get; set; }
        public short? C101 { get; set; }
        public short? C102 { get; set; }
        public short? C103 { get; set; }
        public short? C104 { get; set; }
        public short? C105 { get; set; }
        public short? C106 { get; set; }
        public short? C107 { get; set; }
        public short? C108 { get; set; }
        public short? C109 { get; set; }
        public short? C110 { get; set; }
        public short? C111 { get; set; }
        public short? C112 { get; set; }
        public short? C113 { get; set; }
        public short? C114 { get; set; }
        public short? C115 { get; set; }
        public short? C116 { get; set; }
        public short? C117 { get; set; }
        public short? C118 { get; set; }
        public short? C119 { get; set; }
        public short? C120 { get; set; }
        public short? C121 { get; set; }
        public short? C122 { get; set; }
        public short? C123 { get; set; }
        public short? C124 { get; set; }
        public short? C125 { get; set; }
        public short? C126 { get; set; }
        public short? C127 { get; set; }
        public short? C128 { get; set; }
        public short? C129 { get; set; }
        public short? C130 { get; set; }
        public short? C131 { get; set; }
        public short? C132 { get; set; }
        public short? C133 { get; set; }
        public short? C134 { get; set; }
        public short? C135 { get; set; }
        public short? C136 { get; set; }
        public short? C137 { get; set; }
        public short? C138 { get; set; }
        public short? C139 { get; set; }
        public short? C140 { get; set; }
        public short? C141 { get; set; }
        public short? C142 { get; set; }
        public short? C143 { get; set; }
        public short? C144 { get; set; }
        public short? C145 { get; set; }
        public short? C146 { get; set; }
        public short? C147 { get; set; }
        public short? C148 { get; set; }
        public short? C149 { get; set; }
        public short? C150 { get; set; }
        public short? C151 { get; set; }
        public short? C152 { get; set; }
        public short? C153 { get; set; }
        public short? C154 { get; set; }
        public short? C155 { get; set; }
        public short? C156 { get; set; }
        public short? C157 { get; set; }
        public short? C158 { get; set; }
        public short? C159 { get; set; }
        public short? C160 { get; set; }
        public short? C161 { get; set; }
        public short? C162 { get; set; }
        public short? C163 { get; set; }
        public short? C164 { get; set; }
        public short? C165 { get; set; }
        public short? C166 { get; set; }
        public short? C167 { get; set; }
        public short? C168 { get; set; }
        public short? C169 { get; set; }
        public short? C170 { get; set; }
        public short? C171 { get; set; }
        public short? C172 { get; set; }
        public short? C173 { get; set; }
        public short? C174 { get; set; }
        public short? C175 { get; set; }
        public short? C176 { get; set; }
        public short? C177 { get; set; }
        public short? C178 { get; set; }
        public short? C179 { get; set; }
        public short? C180 { get; set; }
        public short? C181 { get; set; }
        public short? C182 { get; set; }
        public short? C183 { get; set; }
        public short? C184 { get; set; }
        public short? C185 { get; set; }
        public short? C186 { get; set; }
        public short? C187 { get; set; }
        public short? C188 { get; set; }
        public short? C189 { get; set; }
        public short? C190 { get; set; }
        public short? C191 { get; set; }
        public short? C192 { get; set; }
        public short? A1 { get; set; }
        public short? A2 { get; set; }
        public short? A3 { get; set; }
        public short? A4 { get; set; }
        public short? A5 { get; set; }
        public short? A6 { get; set; }
        public short? A7 { get; set; }
        public short? A8 { get; set; }
        public short? A9 { get; set; }
        public short? A10 { get; set; }
        public short? A11 { get; set; }
        public short? A12 { get; set; }
        public short? A13 { get; set; }
        public short? A14 { get; set; }
        public short? A15 { get; set; }
        public short? A16 { get; set; }
        public short? A17 { get; set; }
        public short? A18 { get; set; }
        public short? A19 { get; set; }
        public short? A20 { get; set; }
        public short? A21 { get; set; }
        public short? A22 { get; set; }
        public short? A23 { get; set; }
        public short? A24 { get; set; }
        public short? A25 { get; set; }
        public short? A26 { get; set; }
        public short? A27 { get; set; }
        public short? A28 { get; set; }
        public short? A29 { get; set; }
        public short? A30 { get; set; }
        public short? A31 { get; set; }
        public short? A32 { get; set; }
    }
}
